### ISSUE TITLE
Written Books Support.

### ISSUE THREAD

**Issue by mkromann** [grandwazir/StarterKit#19]
Support for written books would be incredible useful. It is an obvious way to give out standard information when people join the server. A great way to replace the sign madness some servers sport.

**Comment by grandwazir** [comment]
I was waiting for API support to do this but it appears like it is not going to be added soon. I'll look again at implementing this weekend.

**Comment by grandwazir** [comment]
Having just looked at this again and seen this recent CraftBukkit [commit](https://github.com/Bukkit/CraftBukkit/commit/8f12382e8efc8c39a919af9180dd884caf3720ff) it is not practical for me to do this without an official API. I am marking this as blocked until the situation changes.

**Comment by grandwazir** [comment]
Issue fixed in Bukkit. Books now supported.
